# Generated by Django 4.2.1 on 2023-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("firstName", models.CharField(max_length=20)),
                ("lastName", models.CharField(max_length=20)),
                ("phone", models.PositiveIntegerField()),
                ("district", models.CharField(max_length=50)),
                ("streetName", models.CharField(max_length=50)),
                ("buildingNumber", models.PositiveIntegerField()),
                ("additionalInfo", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("price", models.PositiveIntegerField()),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
