# Generated by Django 4.2.1 on 2023-05-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="customer",
            field=models.ManyToManyField(
                blank=True, related_name="customers", to="store.customer"
            ),
        ),
    ]
