# Generated by Django 4.2 on 2023-05-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_delivered_customer_ordered_product_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('line_price', models.IntegerField()),
                ('customer', models.ManyToManyField(blank=True, related_name='customersss', to='store.customer')),
                ('product', models.ManyToManyField(blank=True, related_name='products', to='store.product')),
            ],
        ),
    ]
