# Generated by Django 4.2.1 on 2023-05-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_customer_phone"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="customer",),
    ]
