# Generated by Django 4.2.1 on 2023-05-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_product_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="customer",
            field=models.ManyToManyField(
                blank=True, related_name="customers", to="store.customer"
            ),
        ),
    ]
