# Generated by Django 4.2.1 on 2023-05-17 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_order_remove_product_customer_customer_cart_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="cart",),
        migrations.RemoveField(model_name="customer", name="delivered",),
        migrations.RemoveField(model_name="customer", name="ordered",),
        migrations.RemoveField(model_name="order", name="status",),
        migrations.RemoveField(model_name="order", name="total",),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(blank=True, to="store.product"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.customer",
            ),
        ),
        migrations.DeleteModel(name="OrderItem",),
    ]
