# Generated by Django 4.2.1 on 2023-05-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_remove_customer_cart_remove_customer_delivered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
