# Generated by Django 4.2.1 on 2023-05-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_order_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="cart",
            field=models.ManyToManyField(blank=True, to="store.product"),
        ),
        migrations.AddField(
            model_name="customer",
            name="orderConfirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(name="Order",),
    ]
